# Generated by Django 5.1.6 on 2025-02-25 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(blank=True, max_length=1, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('appointment_date', models.DateField(default=datetime.date.today)),
                ('appointment_time', models.TimeField(unique=True)),
                ('request_details', models.TextField()),
            ],
        ),
    ]
