# Generated by Django 5.1.6 on 2025-02-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='appointment_time',
            field=models.TimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='appointmentrequest',
            unique_together={('appointment_date', 'appointment_time')},
        ),
    ]
