# Generated by Django 5.1.5 on 2025-03-11 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammodel',
            name='occular_exam_information',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.occularexammodel'),
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='prescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.prescriptionmodel'),
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='visual_accuity_information',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.visualaccuitymodel'),
        ),
    ]
