# Generated by Django 5.1.5 on 2025-02-17 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientusermodel',
            name='patient_id',
        ),
    ]
