# Generated by Django 5.1.5 on 2025-03-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_exammodel_occular_exam_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualaccuitymodel',
            name='OS Visual Accuity',
            field=models.DecimalField(choices=[(10, '20/10'), (12.5, '20/12.5'), (16, '20/16'), (20, '20/20'), (25, '20/25'), (32, '20/32'), (40, '20/40'), (50, '20/50'), (63, '20/63'), (80, '20/80'), (100, '20/100'), (125, '20/125'), (160, '20/160'), (200, '20/200')], decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='visualaccuitymodel',
            name='OU Visual Accuity',
            field=models.DecimalField(choices=[(10, '20/10'), (12.5, '20/12.5'), (16, '20/16'), (20, '20/20'), (25, '20/25'), (32, '20/32'), (40, '20/40'), (50, '20/50'), (63, '20/63'), (80, '20/80'), (100, '20/100'), (125, '20/125'), (160, '20/160'), (200, '20/200')], decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='visualaccuitymodel',
            name='Right Eye Measurement',
            field=models.DecimalField(choices=[(10, '20/10'), (12.5, '20/12.5'), (16, '20/16'), (20, '20/20'), (25, '20/25'), (32, '20/32'), (40, '20/40'), (50, '20/50'), (63, '20/63'), (80, '20/80'), (100, '20/100'), (125, '20/125'), (160, '20/160'), (200, '20/200')], decimal_places=1, max_digits=4),
        ),
    ]
