# Generated by Django 5.1.5 on 2025-02-19 00:55

from django.contrib.auth.models import Group
from django.db import migrations


def create_groups(apps, schema_editor):
    Group.objects.get_or_create(name="Patients")
    Group.objects.get_or_create(name="Office Manager")
    Group.objects.get_or_create(name="Ophthalmologist")


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0002_remove_patientusermodel_patient_id"),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
