# Generated by Django 5.1.5 on 2025-03-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_visualaccuitymodel_os_visual_accuity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exammodel',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AddField(
            model_name='exammodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('upcoming', 'Upcoming'), ('waiting', 'In Wait Room'), ('progressing', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=11),
            preserve_default=False,
        ),
    ]
