# Generated by Django 5.1.5 on 2025-03-14 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_alter_exammodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescriptionmodel',
            options={},
        ),
    ]
