# Generated by Django 5.1.5 on 2025-02-26 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_alter_tokenauthmodel_group_managerusermodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenAuthModel',
        ),
    ]
