# Generated by Django 5.1.5 on 2025-03-09 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_delete_tokenauthmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(blank=True, max_length=1, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('appointment_date', models.DateField(default=datetime.date.today)),
                ('appointment_time', models.TimeField()),
                ('request_details', models.TextField()),
            ],
            options={
                'unique_together': {('appointment_date', 'appointment_time')},
            },
        ),
    ]
