# Generated by Django 5.1.5 on 2025-03-15 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_alter_exammodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exammodel',
            options={'ordering': ['-date', '-time'], 'permissions': [('patient', 'Patient Permissions'), ('doctor', 'Doctor Permissions'), ('manager', 'Manager Permissions')]},
        ),
    ]
