# Generated by Django 5.1.5 on 2025-03-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_alter_exammodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionmodel',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='visualaccuitymodel',
            name='prescription',
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('upcoming', 'Upcoming'), ('waiting', 'In Wait Room'), ('progressing', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], max_length=11, null=True),
        ),
    ]
