# Generated by Django 5.1.5 on 2025-03-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_remove_prescriptionmodel_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientusermodel',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patientusermodel',
            name='social_security_number',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
