# Generated by Django 5.1.5 on 2025-03-25 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_remove_patientusermodel_emergency_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycontactmodel',
            name='phone_num',
        ),
        migrations.AddField(
            model_name='emergencycontactmodel',
            name='phone_number',
            field=models.CharField(default=1, max_length=14, validators=[django.core.validators.RegexValidator(message='Phone number must follow regulations', regex='^(?:[(][0-9]{3}[)][. -]|[(][0-9]{3}[)]|[0-9]{3}[. -])[0-9]{3}[ .-][0-9]{4}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insuranceprovidermodel',
            name='zip_code',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Zipcode must be in the format XXXXX or XXXXX-XXXX', regex='^\\d{5}-\\d{4}$|^\\d{5}$')]),
        ),
    ]
