# Generated by Django 5.1.5 on 2025-03-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_remove_emergencycontactmodel_phone_num_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencycontactmodel',
            old_name='email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='emergencycontactmodel',
            old_name='first_name',
            new_name='contact_first_name',
        ),
        migrations.RenameField(
            model_name='emergencycontactmodel',
            old_name='last_name',
            new_name='contact_last_name',
        ),
        migrations.RenameField(
            model_name='emergencycontactmodel',
            old_name='middle_initial',
            new_name='contact_middle_initial',
        ),
        migrations.RenameField(
            model_name='emergencycontactmodel',
            old_name='phone_number',
            new_name='contact_phone_number',
        ),
        migrations.RenameField(
            model_name='emergencycontactmodel',
            old_name='relationship',
            new_name='contact_relationship',
        ),
        migrations.RenameField(
            model_name='emergencycontactmodel',
            old_name='title',
            new_name='contact_title',
        ),
        migrations.RenameField(
            model_name='insuranceprovidermodel',
            old_name='city',
            new_name='insurance_city',
        ),
        migrations.RenameField(
            model_name='insuranceprovidermodel',
            old_name='phone_number',
            new_name='insurance_phone_number',
        ),
        migrations.RenameField(
            model_name='insuranceprovidermodel',
            old_name='provider',
            new_name='insurance_provider',
        ),
        migrations.RenameField(
            model_name='insuranceprovidermodel',
            old_name='state',
            new_name='insurance_state',
        ),
        migrations.RenameField(
            model_name='insuranceprovidermodel',
            old_name='street_address',
            new_name='insurance_street_address',
        ),
        migrations.RenameField(
            model_name='insuranceprovidermodel',
            old_name='zip_code',
            new_name='insurance_zip_code',
        ),
        migrations.AlterField(
            model_name='insuranceprovidermodel',
            name='group_number',
            field=models.IntegerField(),
        ),
    ]
