# Generated by Django 5.1.5 on 2025-03-26 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0015_rename_email_emergencycontactmodel_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontactmodel',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Core.patientusermodel'),
        ),
        migrations.AlterField(
            model_name='insuranceprovidermodel',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Core.patientusermodel'),
        ),
    ]
