# Generated by Django 5.1.5 on 2025-03-26 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0016_alter_emergencycontactmodel_patient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencycontactmodel',
            old_name='contact_title',
            new_name='Contact title',
        ),
    ]
