# Generated by Django 5.1.5 on 2025-03-26 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0017_rename_contact_title_emergencycontactmodel_contact_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencycontactmodel',
            old_name='Contact title',
            new_name='contact_title',
        ),
    ]
