# Generated by Django 5.1.5 on 2025-03-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0018_rename_contact_title_emergencycontactmodel_contact_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceprovidermodel',
            name='primary_care_provider',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='image_of_left_eye',
            field=models.ImageField(default=1, upload_to='left_eye/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='image_of_right_eye',
            field=models.ImageField(default=1, upload_to='right_eye/'),
            preserve_default=False,
        ),
    ]
