# Generated by Django 5.1.5 on 2025-03-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0019_insuranceprovidermodel_primary_care_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occularexammodel',
            name='other_information',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
