# Generated by Django 5.1.5 on 2025-04-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0021_alter_exammodel_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammodel',
            name='time',
            field=models.TimeField(choices=[('08:00:00', '8:00 AM'), ('08:30:00', '8:30 AM'), ('09:00:00', '9:00 AM'), ('09:30:00', '9:30 AM'), ('10:00:00', '10:00 AM'), ('10:30:00', '10:30 AM'), ('11:00:00', '11:00 AM'), ('11:30:00', '11:30 AM'), ('12:00:00', '12:00 PM'), ('12:30:00', '12:30 PM'), ('13:00:00', '1:00 PM'), ('13:30:00', '1:30 PM'), ('14:00:00', '2:00 PM'), ('14:30:00', '2:30 PM'), ('15:00:00', '3:00 PM'), ('15:30:00', '3:30 PM'), ('16:00:00', '4:00 PM'), ('16:30:00', '4:30 PM'), ('17:00:00', '5:00 PM')]),
        ),
    ]
