# Generated by Django 5.1.5 on 2025-04-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0022_alter_exammodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammodel',
            name='time',
            field=models.TimeField(),
        ),
    ]
