# Generated by Django 5.1.5 on 2025-04-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0023_alter_exammodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Upcoming', 'Upcoming'), ('In Wait Room', 'In Wait Room'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='occularexammodel',
            name='image_of_left_eye',
            field=models.ImageField(upload_to='database/left_eye/'),
        ),
        migrations.AlterField(
            model_name='occularexammodel',
            name='image_of_right_eye',
            field=models.ImageField(upload_to='database/right_eye/'),
        ),
        migrations.AlterField(
            model_name='occularexammodel',
            name='other_information',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
