# Generated by Django 5.1.5 on 2025-04-03 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0024_alter_exammodel_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exammodel',
            unique_together={('date', 'time', 'doctor')},
        ),
    ]
