# Generated by Django 5.1.5 on 2025-04-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0025_alter_exammodel_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Upcoming', 'Upcoming'), ('In Wait Room', 'In Wait Room'), ('Exam In Progress', 'Exam In Progress'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], max_length=16, null=True),
        ),
    ]
