# Generated by Django 5.1.5 on 2025-04-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0026_alter_exammodel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visualaccuitymodel',
            old_name='Right Eye Measurement',
            new_name='OD Measurement',
        ),
        migrations.RenameField(
            model_name='visualaccuitymodel',
            old_name='Corrector Indicator',
            new_name='OS Corrector Indicator',
        ),
        migrations.AddField(
            model_name='exammodel',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
