# Generated by Django 5.1.5 on 2025-04-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0027_rename_right_eye_measurement_visualaccuitymodel_od_measurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualaccuitymodel',
            name='OU Corrector Indicator',
            field=models.CharField(blank=True, choices=[('cc', 'cc (with)'), ('sc', 'sc (without)')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visualaccuitymodel',
            name='OU Pinhole Occluder',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visualaccuitymodel',
            name='OU Visual Accuity',
            field=models.DecimalField(blank=True, choices=[(10, '20/10'), (12.5, '20/12.5'), (16, '20/16'), (20, '20/20'), (25, '20/25'), (32, '20/32'), (40, '20/40'), (50, '20/50'), (63, '20/63'), (80, '20/80'), (100, '20/100'), (125, '20/125'), (160, '20/160'), (200, '20/200')], decimal_places=1, max_digits=4, null=True),
        ),
    ]
