# Generated by Django 5.1.5 on 2025-04-04 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0028_alter_visualaccuitymodel_ou_corrector_indicator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occularexammodel',
            name='20D BIO Lens',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='78D Lens',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='90D Lens',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='ARMD Segment',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='DFE Contraindicated',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='DFE Declined',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='DFE Not Indicated',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='DFE refused AME',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='DFE to be Rescheduled',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='Diabeti Eval Segment',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='Direct Opthalmoscope',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='Evaluation Performed',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='Fundus Imaging Performed',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='HTL Evaluation Segment',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='Macula Segment',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='Misc Retina Segment',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='Nerve Fiber Layer',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='OD Cup-Disc Horizontal Ratio',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='OD Cup-Disc Vertical Ratio',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='OD Deep/Lamina',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='OD Glial Remnants',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='OD Muyelination',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='OD Optic Pit',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='OD Oval',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='OD Peripap Atrophy',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='OD Pigment Crescent',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='OD Reflex',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='OD Round',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='OD Scleral Crescent',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='OD Shallow',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='OD Temp. sloping',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='OD undermining',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='OS Cup-Disc Horizontal Ratio',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='OS Cup-Disc Vertical Ratio',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='OS Deep/Lamina',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='OS Glial Remnants',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='OS Muyelination',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='OS Optic Pit',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='OS Oval',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='OS Peripap Atrophy',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='OS Pigment Crescent',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='OS Reflex',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='OS Round',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='OS Scleral Crescent',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='OS Shallow',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='OS Sponeaneous Venous Pulsation',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='OS Temp. sloping',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='OS undermining',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='Optic Nerve',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='Other',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='PR 2.2 BIO Lens',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='Patient Advised of effects of DFE',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='Peripheral Retina Segment',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='Posterior Pole Segment',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='Recent DFE',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='Scleral Depression',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='Vasculature Segment',
        ),
        migrations.RemoveField(
            model_name='occularexammodel',
            name='Vitreous Segment',
        ),
        migrations.RemoveField(
            model_name='visualaccuitymodel',
            name='OD Corrector Indicator',
        ),
        migrations.RemoveField(
            model_name='visualaccuitymodel',
            name='OD Measurement',
        ),
        migrations.RemoveField(
            model_name='visualaccuitymodel',
            name='OD Pinhole Occluder',
        ),
        migrations.RemoveField(
            model_name='visualaccuitymodel',
            name='OS Corrector Indicator',
        ),
        migrations.RemoveField(
            model_name='visualaccuitymodel',
            name='OS Pinhole Occluder',
        ),
        migrations.RemoveField(
            model_name='visualaccuitymodel',
            name='OS Visual Accuity',
        ),
        migrations.RemoveField(
            model_name='visualaccuitymodel',
            name='OU Corrector Indicator',
        ),
        migrations.RemoveField(
            model_name='visualaccuitymodel',
            name='OU Pinhole Occluder',
        ),
        migrations.RemoveField(
            model_name='visualaccuitymodel',
            name='OU Visual Accuity',
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='PR22_lens',
            field=models.BooleanField(default=False, verbose_name='PR 2.2 BIO Lens'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='advised',
            field=models.BooleanField(default=False, verbose_name='Patient Advised of effects of DFE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='armd_segment',
            field=models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('HIGH', 'HIGH'), ('NORM', 'NORM'), ('LOW', 'LOW'), ('NOT CHECKED', 'NOT CHECKED')], default=False, max_length=255, verbose_name='ARMD Segment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='biabeti_eval_segment',
            field=models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('HIGH', 'HIGH'), ('NORM', 'NORM'), ('LOW', 'LOW'), ('NOT CHECKED', 'NOT CHECKED')], default=False, max_length=255, verbose_name='Diabeti Eval Segment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='contraindicated',
            field=models.BooleanField(default=False, verbose_name='DFE Contraindicated'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='d20_lens',
            field=models.BooleanField(default=False, verbose_name='20D BIO Lens'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='d78_lens',
            field=models.BooleanField(default=False, verbose_name='78D Lens'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='d90_lens',
            field=models.BooleanField(default=False, verbose_name='90D Lens'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='declined',
            field=models.BooleanField(default=False, verbose_name='DFE Declined'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='fundus_record',
            field=models.CharField(choices=[('Not Performed', 'Not Performed'), ('Small Pupil BIO', 'Small Pupil BIO'), ('Dilated Eval', 'Dilated Eval'), ('Undilated Eval', 'Undilated Eval'), ('Optomap Imaging', 'Optomap Imaging'), ('DFE with Optomap', 'DFE with Optomap')], default=False, max_length=255, verbose_name='Evaluation Performed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='htl_eval_segment',
            field=models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('HIGH', 'HIGH'), ('NORM', 'NORM'), ('LOW', 'LOW'), ('NOT CHECKED', 'NOT CHECKED')], default=False, max_length=255, verbose_name='HTL Evaluation Segment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='imaging',
            field=models.BooleanField(default=False, verbose_name='Fundus Imaging Performed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='left_foveal_reflex',
            field=models.CharField(choices=[('+', '+'), ('-', '-'), ('X', 'X')], default=False, max_length=1, verbose_name='OS Reflex'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='left_venous_pulsation',
            field=models.CharField(choices=[('+', '+'), ('-', '-'), ('X', 'X')], default=False, max_length=1, verbose_name='OS Sponeaneous Venous Pulsation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='macula_segment',
            field=models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('HIGH', 'HIGH'), ('NORM', 'NORM'), ('LOW', 'LOW'), ('NOT CHECKED', 'NOT CHECKED')], default=False, max_length=255, verbose_name='Macula Segment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='misc_retina_segment',
            field=models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('HIGH', 'HIGH'), ('NORM', 'NORM'), ('LOW', 'LOW'), ('NOT CHECKED', 'NOT CHECKED')], default=False, max_length=255, verbose_name='Misc Retina Segment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='nerve_fiber',
            field=models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('HIGH', 'HIGH'), ('NORM', 'NORM'), ('LOW', 'LOW'), ('NOT CHECKED', 'NOT CHECKED')], default=False, max_length=255, verbose_name='Nerve Fiber Layer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='not_indicated',
            field=models.BooleanField(default=False, verbose_name='DFE Not Indicated'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='od_atrophy',
            field=models.BooleanField(default=False, verbose_name='OD Peripap Atrophy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='od_cup_ratio_horizontal',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='OD Cup-Disc Horizontal Ratio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='od_cup_ratio_vertical',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='OD Cup-Disc Vertical Ratio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='od_deep',
            field=models.BooleanField(default=False, verbose_name='OD Deep/Lamina'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='od_muyelination',
            field=models.BooleanField(default=False, verbose_name='OD Muyelination'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='od_oval',
            field=models.BooleanField(default=False, verbose_name='OD Oval'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='od_pigment',
            field=models.BooleanField(default=False, verbose_name='OD Pigment Crescent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='od_pit',
            field=models.BooleanField(default=False, verbose_name='OD Optic Pit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='od_remnants',
            field=models.BooleanField(default=False, verbose_name='OD Glial Remnants'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='od_round',
            field=models.BooleanField(default=False, verbose_name='OD Round'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='od_scleral',
            field=models.BooleanField(default=False, verbose_name='OD Scleral Crescent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='od_shallow',
            field=models.BooleanField(default=False, verbose_name='OD Shallow'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='od_temp',
            field=models.BooleanField(default=False, verbose_name='OD Temp. sloping'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='od_under',
            field=models.BooleanField(default=False, verbose_name='OD undermining'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='ophthalmoscope',
            field=models.BooleanField(default=False, verbose_name='Direct Opthalmoscope'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='optic_nerve',
            field=models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('HIGH', 'HIGH'), ('NORM', 'NORM'), ('LOW', 'LOW'), ('NOT CHECKED', 'NOT CHECKED')], default=False, max_length=255, verbose_name='Optic Nerve'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='os_atrophy',
            field=models.BooleanField(default=False, verbose_name='OS Peripap Atrophy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='os_cup_ratio_horizontal',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='OS Cup-Disc Horizontal Ratio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='os_cup_ratio_vertical',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='OS Cup-Disc Vertical Ratio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='os_deep',
            field=models.BooleanField(default=False, verbose_name='OS Deep/Lamina'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='os_muyelination',
            field=models.BooleanField(default=False, verbose_name='OS Muyelination'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='os_oval',
            field=models.BooleanField(default=False, verbose_name='OS Oval'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='os_pigment',
            field=models.BooleanField(default=False, verbose_name='OS Pigment Crescent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='os_pit',
            field=models.BooleanField(default=False, verbose_name='OS Optic Pit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='os_remnants',
            field=models.BooleanField(default=False, verbose_name='OS Glial Remnants'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='os_round',
            field=models.BooleanField(default=False, verbose_name='OS Round'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='os_scleral',
            field=models.BooleanField(default=False, verbose_name='OS Scleral Crescent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='os_shallow',
            field=models.BooleanField(default=False, verbose_name='OS Shallow'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='os_temp',
            field=models.BooleanField(default=False, verbose_name='OS Temp. sloping'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='os_under',
            field=models.BooleanField(default=False, verbose_name='OS undermining'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='peripheral_retina_segment',
            field=models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('HIGH', 'HIGH'), ('NORM', 'NORM'), ('LOW', 'LOW'), ('NOT CHECKED', 'NOT CHECKED')], default=False, max_length=255, verbose_name='Peripheral Retina Segment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='posterior_pole_segment',
            field=models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('HIGH', 'HIGH'), ('NORM', 'NORM'), ('LOW', 'LOW'), ('NOT CHECKED', 'NOT CHECKED')], default=False, max_length=255, verbose_name='Posterior Pole Segment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='recent',
            field=models.BooleanField(default=False, verbose_name='Recent DFE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='refused',
            field=models.BooleanField(default=False, verbose_name='DFE refused AME'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='rescheduled',
            field=models.BooleanField(default=False, verbose_name='DFE to be Rescheduled'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='right_venous_pulsation',
            field=models.CharField(choices=[('+', '+'), ('-', '-'), ('X', 'X')], default=False, max_length=1, verbose_name='OD Reflex'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='scleral_depression',
            field=models.BooleanField(default=False, verbose_name='Scleral Depression'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='vasculature_segment',
            field=models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('HIGH', 'HIGH'), ('NORM', 'NORM'), ('LOW', 'LOW'), ('NOT CHECKED', 'NOT CHECKED')], default=False, max_length=255, verbose_name='Vasculature Segment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='vitreous_segment',
            field=models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('HIGH', 'HIGH'), ('NORM', 'NORM'), ('LOW', 'LOW'), ('NOT CHECKED', 'NOT CHECKED')], default=False, max_length=255, verbose_name='Vitreous Segment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visualaccuitymodel',
            name='corrector_indicator_both',
            field=models.CharField(blank=True, choices=[('cc', 'cc (with)'), ('sc', 'sc (without)')], max_length=255, null=True, verbose_name='OU Corrector Indicator'),
        ),
        migrations.AddField(
            model_name='visualaccuitymodel',
            name='corrector_indicator_left',
            field=models.CharField(choices=[('cc', 'cc (with)'), ('sc', 'sc (without)')], default=False, max_length=255, verbose_name='OS Corrector Indicator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visualaccuitymodel',
            name='corrector_indicator_right',
            field=models.CharField(choices=[('cc', 'cc (with)'), ('sc', 'sc (without)')], default=False, max_length=255, verbose_name='OD Corrector Indicator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visualaccuitymodel',
            name='pinhole_both',
            field=models.BooleanField(blank=True, null=True, verbose_name='OU Pinhole Occluder'),
        ),
        migrations.AddField(
            model_name='visualaccuitymodel',
            name='pinhole_left',
            field=models.BooleanField(default=False, verbose_name='OS Pinhole Occluder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visualaccuitymodel',
            name='pinhole_right',
            field=models.BooleanField(default=False, verbose_name='OD Pinhole Occluder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visualaccuitymodel',
            name='visual_acuity_measure_both',
            field=models.DecimalField(blank=True, choices=[(10, '20/10'), (12.5, '20/12.5'), (16, '20/16'), (20, '20/20'), (25, '20/25'), (32, '20/32'), (40, '20/40'), (50, '20/50'), (63, '20/63'), (80, '20/80'), (100, '20/100'), (125, '20/125'), (160, '20/160'), (200, '20/200')], decimal_places=1, max_digits=4, null=True, verbose_name='OU Visual Accuity'),
        ),
        migrations.AddField(
            model_name='visualaccuitymodel',
            name='visual_acuity_measure_left',
            field=models.DecimalField(choices=[(10, '20/10'), (12.5, '20/12.5'), (16, '20/16'), (20, '20/20'), (25, '20/25'), (32, '20/32'), (40, '20/40'), (50, '20/50'), (63, '20/63'), (80, '20/80'), (100, '20/100'), (125, '20/125'), (160, '20/160'), (200, '20/200')], decimal_places=1, default=False, max_digits=4, verbose_name='OS Visual Accuity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visualaccuitymodel',
            name='visual_acuity_measure_right',
            field=models.DecimalField(choices=[(10, '20/10'), (12.5, '20/12.5'), (16, '20/16'), (20, '20/20'), (25, '20/25'), (32, '20/32'), (40, '20/40'), (50, '20/50'), (63, '20/63'), (80, '20/80'), (100, '20/100'), (125, '20/125'), (160, '20/160'), (200, '20/200')], decimal_places=1, default=False, max_digits=4, verbose_name='OD Measurement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='other',
            field=models.BooleanField(default=False, verbose_name='Other'),
            preserve_default=False,
        ),
    ]
