# Generated by Django 5.1.5 on 2025-04-08 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0029_remove_occularexammodel_20d_bio_lens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exammodel',
            name='visual_accuity_information',
        ),
        migrations.RemoveField(
            model_name='visualaccuitymodel',
            name='corrector_indicator_both',
        ),
        migrations.RemoveField(
            model_name='visualaccuitymodel',
            name='corrector_indicator_left',
        ),
        migrations.RemoveField(
            model_name='visualaccuitymodel',
            name='corrector_indicator_right',
        ),
        migrations.RemoveField(
            model_name='visualaccuitymodel',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='visualaccuitymodel',
            name='pinhole_both',
        ),
        migrations.RemoveField(
            model_name='visualaccuitymodel',
            name='pinhole_left',
        ),
        migrations.RemoveField(
            model_name='visualaccuitymodel',
            name='pinhole_right',
        ),
        migrations.AddField(
            model_name='exammodel',
            name='visual_accuity_aided_distance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_aided_distance', to='Core.visualaccuitymodel'),
        ),
        migrations.AddField(
            model_name='exammodel',
            name='visual_accuity_aided_near',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_aided_near', to='Core.visualaccuitymodel'),
        ),
        migrations.AddField(
            model_name='exammodel',
            name='visual_accuity_aided_string_both_distance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exammodel',
            name='visual_accuity_aided_string_both_near',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exammodel',
            name='visual_accuity_aided_string_left_distance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exammodel',
            name='visual_accuity_aided_string_left_near',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exammodel',
            name='visual_accuity_aided_string_right_distance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exammodel',
            name='visual_accuity_aided_string_right_near',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exammodel',
            name='visual_accuity_pinhole_aided_distance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_aided_ph_distance', to='Core.visualaccuitymodel'),
        ),
        migrations.AddField(
            model_name='exammodel',
            name='visual_accuity_pinhole_aided_near',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_aided_ph_near', to='Core.visualaccuitymodel'),
        ),
        migrations.AddField(
            model_name='exammodel',
            name='visual_accuity_pinhole_unaided_distance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_unaided_ph_distance', to='Core.visualaccuitymodel'),
        ),
        migrations.AddField(
            model_name='exammodel',
            name='visual_accuity_pinhole_unaided_near',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_unaided_ph_near', to='Core.visualaccuitymodel'),
        ),
        migrations.AddField(
            model_name='exammodel',
            name='visual_accuity_unaided_distance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_unaided_distance', to='Core.visualaccuitymodel'),
        ),
        migrations.AddField(
            model_name='exammodel',
            name='visual_accuity_unaided_near',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_unaided_near', to='Core.visualaccuitymodel'),
        ),
        migrations.AddField(
            model_name='exammodel',
            name='visual_accuity_unaided_string_both_distance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exammodel',
            name='visual_accuity_unaided_string_both_near',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exammodel',
            name='visual_accuity_unaided_string_left_distance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exammodel',
            name='visual_accuity_unaided_string_left_near',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exammodel',
            name='visual_accuity_unaided_string_right_distance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exammodel',
            name='visual_accuity_unaided_string_right_near',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Upcoming', 'Upcoming'), ('In Wait Room', 'In Wait Room'), ('Exam In Progress', 'Exam In Progress'), ('Completed', 'Completed')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='visualaccuitymodel',
            name='visual_acuity_measure_left',
            field=models.DecimalField(blank=True, choices=[(10, '20/10'), (12.5, '20/12.5'), (16, '20/16'), (20, '20/20'), (25, '20/25'), (32, '20/32'), (40, '20/40'), (50, '20/50'), (63, '20/63'), (80, '20/80'), (100, '20/100'), (125, '20/125'), (160, '20/160'), (200, '20/200')], decimal_places=1, max_digits=4, null=True, verbose_name='OS Visual Accuity'),
        ),
        migrations.AlterField(
            model_name='visualaccuitymodel',
            name='visual_acuity_measure_right',
            field=models.DecimalField(blank=True, choices=[(10, '20/10'), (12.5, '20/12.5'), (16, '20/16'), (20, '20/20'), (25, '20/25'), (32, '20/32'), (40, '20/40'), (50, '20/50'), (63, '20/63'), (80, '20/80'), (100, '20/100'), (125, '20/125'), (160, '20/160'), (200, '20/200')], decimal_places=1, max_digits=4, null=True, verbose_name='OD Measurement'),
        ),
    ]
