# Generated by Django 5.1.5 on 2025-04-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0030_remove_exammodel_visual_accuity_information_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionmodel',
            name='visual_acuity',
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='od_visual_acuity_distance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='od_visual_acuity_near',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='os_visual_acuity_distance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='os_visual_acuity_near',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
