# Generated by Django 5.1.5 on 2025-04-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0031_remove_prescriptionmodel_visual_acuity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammodel',
            name='visual_accuity_aided_string_both_distance',
            field=models.CharField(blank=True, default='Not Recorded', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='visual_accuity_aided_string_both_near',
            field=models.CharField(blank=True, default='Not Recorded', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='visual_accuity_aided_string_left_distance',
            field=models.CharField(blank=True, default='Not Recorded', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='visual_accuity_aided_string_left_near',
            field=models.CharField(blank=True, default='Not Recorded', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='visual_accuity_aided_string_right_distance',
            field=models.CharField(blank=True, default='Not Recorded', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='visual_accuity_aided_string_right_near',
            field=models.CharField(blank=True, default='Not Recorded', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='visual_accuity_unaided_string_both_distance',
            field=models.CharField(blank=True, default='Not Recorded', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='visual_accuity_unaided_string_both_near',
            field=models.CharField(blank=True, default='Not Recorded', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='visual_accuity_unaided_string_left_distance',
            field=models.CharField(blank=True, default='Not Recorded', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='visual_accuity_unaided_string_left_near',
            field=models.CharField(blank=True, default='Not Recorded', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='visual_accuity_unaided_string_right_distance',
            field=models.CharField(blank=True, default='Not Recorded', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='visual_accuity_unaided_string_right_near',
            field=models.CharField(blank=True, default='Not Recorded', max_length=255, null=True),
        ),
    ]
