# Generated by Django 5.1.5 on 2025-04-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0033_alter_exammodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammodel',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('upcoming', 'Upcoming'), ('waiting', 'In Wait Room'), ('progressing', 'Exam In Progress'), ('complete', 'Completed')], max_length=16, null=True),
        ),
    ]
