# Generated by Django 5.1.5 on 2025-04-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0035_rename_biabeti_eval_segment_occularexammodel_diabeti_eval_segment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='occularexammodel',
            name='right_foveal_reflex',
            field=models.CharField(choices=[('+', '+'), ('-', '-'), ('X', 'X')], default='+', max_length=1, verbose_name='OD Reflex'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='occularexammodel',
            name='right_venous_pulsation',
            field=models.CharField(choices=[('+', '+'), ('-', '-'), ('X', 'X')], max_length=1, verbose_name='OD Venous Pulsation'),
        ),
    ]
