# Generated by Django 5.1.5 on 2025-04-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0038_alter_prescriptionmodel_od_visual_acuity_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionmodel',
            name='od_visual_acuity_distance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionmodel',
            name='od_visual_acuity_near',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionmodel',
            name='os_visual_acuity_distance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionmodel',
            name='os_visual_acuity_near',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
