# Generated by Django 5.1.5 on 2025-04-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0042_alter_visualaccuitymodel_visual_acuity_measure_both_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exammodel',
            name='completed',
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('upcoming', 'Upcoming'), ('waiting', 'In Wait Room'), ('progressing', 'Exam In Progress'), ('postexam', 'Post Examination'), ('complete', 'Completed')], max_length=16, null=True),
        ),
    ]
