# Generated by Django 5.1.5 on 2025-04-13 06:09

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0044_alter_occularexammodel_image_of_left_eye_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammodel',
            name='status',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, choices=[('pending', 'Pending'), ('upcoming', 'Upcoming'), ('waiting', 'In Wait Room'), ('progressing', 'Exam In Progress'), ('postexam', 'Post Examination'), ('complete', 'Completed')], max_length=16, null=True)),
        ),
    ]
