# Generated by Django 5.1.5 on 2025-04-13 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0047_alter_occularexammodel_pr22_lens_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exammodel',
            unique_together={('date', 'time', 'doctor'), ('patient', 'date', 'time')},
        ),
    ]
