# Generated by Django 5.1.5 on 2025-04-13 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0048_alter_exammodel_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exammodel',
            unique_together={('date', 'time', 'doctor'), ('patient', 'date')},
        ),
    ]
