# Generated by Django 5.1.5 on 2025-04-14 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0049_alter_exammodel_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceprovidermodel',
            name='group_number',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='patientusermodel',
            name='zip_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Zipcode must be in the format XXXXX or XXXXX-XXXX', regex='^\\d{5}-\\d{4}$|^\\d{5}$')]),
        ),
    ]
