# Generated by Django 5.1.5 on 2025-04-14 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0050_alter_insuranceprovidermodel_group_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceprovidermodel',
            name='co_pay',
            field=models.DecimalField(decimal_places=2, max_digits=255, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
