# Generated by Django 5.1.5 on 2025-04-15 02:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0051_alter_insuranceprovidermodel_co_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceprovidermodel',
            name='insurance_zip_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Zipcode must be in the format XXXXX or XXXXX-XXXX', regex='^\\d{5}-\\d{4}$|^\\d{5}$')]),
        ),
    ]
