# Generated by Django 5.1.5 on 2025-04-15 03:28

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0052_alter_insuranceprovidermodel_insurance_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='occularexammodel',
            name='custom_1',
            field=django_cryptography.fields.encrypt(models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('HIGH', 'HIGH'), ('NORM', 'NORM'), ('LOW', 'LOW'), ('NOT CHECKED', 'NOT CHECKED')], default='j', max_length=255, verbose_name='Custom 1')),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='custom_1_input',
            field=django_cryptography.fields.encrypt(models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('HIGH', 'HIGH'), ('NORM', 'NORM'), ('LOW', 'LOW'), ('NOT CHECKED', 'NOT CHECKED')], default='j', max_length=255, verbose_name='Custom 1')),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='custom_2',
            field=django_cryptography.fields.encrypt(models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('HIGH', 'HIGH'), ('NORM', 'NORM'), ('LOW', 'LOW'), ('NOT CHECKED', 'NOT CHECKED')], default='j', max_length=255, verbose_name='Custom 2')),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='custom_2_input',
            field=django_cryptography.fields.encrypt(models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('HIGH', 'HIGH'), ('NORM', 'NORM'), ('LOW', 'LOW'), ('NOT CHECKED', 'NOT CHECKED')], default='j', max_length=255, verbose_name='Custom 1')),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='custom_3',
            field=django_cryptography.fields.encrypt(models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('HIGH', 'HIGH'), ('NORM', 'NORM'), ('LOW', 'LOW'), ('NOT CHECKED', 'NOT CHECKED')], default='j', max_length=255, verbose_name='Custom 3')),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occularexammodel',
            name='custom_3_input',
            field=django_cryptography.fields.encrypt(models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('HIGH', 'HIGH'), ('NORM', 'NORM'), ('LOW', 'LOW'), ('NOT CHECKED', 'NOT CHECKED')], default='j', max_length=255, verbose_name='Custom 1')),
            preserve_default=False,
        ),
    ]
