# Generated by Django 5.1.5 on 2025-04-15 03:30

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0053_occularexammodel_custom_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occularexammodel',
            name='custom_1',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, choices=[('CRITICAL', 'CRITICAL'), ('HIGH', 'HIGH'), ('NORM', 'NORM'), ('LOW', 'LOW'), ('NOT CHECKED', 'NOT CHECKED')], max_length=255, null=True, verbose_name='Custom 1')),
        ),
        migrations.AlterField(
            model_name='occularexammodel',
            name='custom_1_input',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='Custom 1')),
        ),
        migrations.AlterField(
            model_name='occularexammodel',
            name='custom_2',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, choices=[('CRITICAL', 'CRITICAL'), ('HIGH', 'HIGH'), ('NORM', 'NORM'), ('LOW', 'LOW'), ('NOT CHECKED', 'NOT CHECKED')], max_length=255, null=True, verbose_name='Custom 2')),
        ),
        migrations.AlterField(
            model_name='occularexammodel',
            name='custom_2_input',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='Custom 1')),
        ),
        migrations.AlterField(
            model_name='occularexammodel',
            name='custom_3',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, choices=[('CRITICAL', 'CRITICAL'), ('HIGH', 'HIGH'), ('NORM', 'NORM'), ('LOW', 'LOW'), ('NOT CHECKED', 'NOT CHECKED')], max_length=255, null=True, verbose_name='Custom 3')),
        ),
        migrations.AlterField(
            model_name='occularexammodel',
            name='custom_3_input',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='Custom 1')),
        ),
    ]
