# Generated by Django 5.1.5 on 2025-04-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0054_alter_occularexammodel_custom_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientusermodel',
            name='treatments',
            field=models.CharField(blank=True, max_length=65535, null=True),
        ),
    ]
