# Generated by Django 5.1.5 on 2025-04-15 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0055_patientusermodel_treatments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientusermodel',
            name='treatments',
        ),
        migrations.CreateModel(
            name='TreatmentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatments', models.CharField(blank=True, max_length=65535, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Core.patientusermodel')),
            ],
        ),
    ]
