# Generated by Django 5.1.5 on 2025-04-15 22:41

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0056_remove_patientusermodel_treatments_treatmentsmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="occularexammodel",
            name="image_of_left_eye_2",
            field=django_cryptography.fields.encrypt(
                models.ImageField(default=1, upload_to="left_eye/")
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="occularexammodel",
            name="image_of_left_eye_3",
            field=django_cryptography.fields.encrypt(
                models.ImageField(default=1, upload_to="left_eye/")
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="occularexammodel",
            name="image_of_right_eye_2",
            field=django_cryptography.fields.encrypt(
                models.ImageField(default=1, upload_to="right_eye/")
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="occularexammodel",
            name="image_of_right_eye_3",
            field=django_cryptography.fields.encrypt(
                models.ImageField(default=1, upload_to="right_eye/")
            ),
            preserve_default=False,
        ),
    ]
