# Generated by Django 5.1.5 on 2025-04-18 18:20

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0057_occularexammodel_image_of_left_eye_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occularexammodel',
            name='image_of_left_eye_2',
            field=django_cryptography.fields.encrypt(models.ImageField(blank=True, null=True, upload_to='left_eye/')),
        ),
        migrations.AlterField(
            model_name='occularexammodel',
            name='image_of_left_eye_3',
            field=django_cryptography.fields.encrypt(models.ImageField(blank=True, null=True, upload_to='left_eye/')),
        ),
        migrations.AlterField(
            model_name='occularexammodel',
            name='image_of_right_eye_2',
            field=django_cryptography.fields.encrypt(models.ImageField(blank=True, null=True, upload_to='right_eye/')),
        ),
        migrations.AlterField(
            model_name='occularexammodel',
            name='image_of_right_eye_3',
            field=django_cryptography.fields.encrypt(models.ImageField(blank=True, null=True, upload_to='right_eye/')),
        ),
    ]
