# Generated by Django 5.1.5 on 2025-04-26 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0058_alter_occularexammodel_image_of_left_eye_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceClaimModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_details', models.TextField(blank=True, default=None, max_length=65535, null=True)),
                ('cost_breakdown', models.TextField(blank=True, default=None, max_length=65535, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.exammodel')),
            ],
        ),
    ]
