# Generated by Django 5.1.5 on 2025-04-27 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0059_insuranceclaimmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceclaimmodel',
            name='exam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Core.exammodel'),
        ),
    ]
