name: Check

on:
    push:
        branches:
            - main

jobs:
    check:
        runs-on: ubuntu-latest
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
            cancel-in-progress: true
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Run checks
              uses: devcontainers/ci@v0.3
              with:
                  runCmd: task
